import React from "react";
import "./PrivacyPolicy.css";

const LossBossTerms = () => {
  return (
    <main className="privacy-policy">
      <div className="privacy-policy-container">
        <div className="privacy-policy-header">
          <h1>Terms of Use for LossBoss</h1>
          <p className="last-updated"><strong>Last updated: July 22, 2026</strong></p>
        </div>

        <section className="policy-section">
          <h2>Agreement</h2>
          <p>
            These Terms of Use ("Terms") govern your use of the LossBoss mobile application (the
            "App"), operated by Ingenuity Labs LLC. By downloading or using the App you agree to
            these Terms. If you do not agree, do not use the App.
          </p>
        </section>

        <section className="policy-section">
          <h2>Not Medical Advice</h2>
          <p>
            <strong>LossBoss is a wellness and lifestyle app, not a medical service.</strong> The
            App's coaching, calorie targets, meal suggestions, workout plans, and educational
            content are general information and are not medical advice, diagnosis, or treatment.
            Calorie and nutrition estimates (including AI photo estimates) are approximations.
            Always consult a qualified healthcare provider before starting a weight-loss program,
            especially if you are pregnant or nursing, under 18, have or suspect an eating disorder,
            have any medical condition, or take medication (including GLP-1 medications). Stop and
            seek medical attention if you experience concerning symptoms while exercising or
            dieting. The App is intended for adults.
          </p>
        </section>

        <section className="policy-section">
          <h2>AI-Generated Content</h2>
          <p>
            Coaching replies are generated by artificial intelligence in the personality style you
            select, including optional "tough love" styles that use blunt or teasing language you
            have explicitly opted into. AI output can be inaccurate. Use your judgment and do not
            rely on it as professional advice. You can change the coach personality at any time in
            Settings.
          </p>
        </section>

        <section className="policy-section">
          <h2>Subscriptions</h2>
          <p>
            LossBoss offers auto-renewing subscriptions ("LossBoss Pro") that unlock AI features,
            billed through your Apple App Store account. Where offered, new subscribers receive a
            free trial (e.g., 7 days); you can cancel during the trial without charge. Subscriptions
            renew automatically unless cancelled at least 24 hours before the end of the current
            period. Manage or cancel in iOS Settings → Apple ID → Subscriptions. Prices are shown in
            the App before purchase and may change with notice. Refunds are handled by Apple.
          </p>
        </section>

        <section className="policy-section">
          <h2>Acceptable Use</h2>
          <p>
            You agree not to misuse the App, including attempting to reverse engineer it, abuse or
            overload the AI relay service, or use the App for any unlawful purpose. We may suspend
            AI features in cases of abuse.
          </p>
        </section>

        <section className="policy-section">
          <h2>Intellectual Property</h2>
          <p>
            The App, including its design, code, branding, and content, is owned by Ingenuity Labs
            LLC and protected by law. These Terms grant you a personal, non-transferable license to
            use the App on your Apple devices.
          </p>
        </section>

        <section className="policy-section">
          <h2>Disclaimer of Warranties; Limitation of Liability</h2>
          <p>
            The App is provided "as is" without warranties of any kind. To the maximum extent
            permitted by law, Ingenuity Labs LLC is not liable for any indirect, incidental, or
            consequential damages arising from your use of the App, including reliance on its
            estimates or AI-generated content. Our total liability shall not exceed the amount you
            paid for the App in the twelve months preceding the claim.
          </p>
        </section>

        <section className="policy-section">
          <h2>Changes</h2>
          <p>
            We may update these Terms from time to time. Continued use of the App after changes
            constitutes acceptance. Material changes will be reflected by the "Last updated" date
            above.
          </p>
        </section>

        <section className="policy-section">
          <h2>Contact</h2>
          <p>
            Questions about these Terms? Contact us at{" "}
            <a href="mailto:ethan@ingenuitylabs.net">ethan@ingenuitylabs.net</a>.
          </p>
        </section>
      </div>
    </main>
  );
};

export default LossBossTerms;
